services:
  - type: web
    name: Estimator
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_RESTRICTED_KEY
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: CORS_ORIGIN
        value: https://estimator.tamayenterprises.com
